[package]
name = "distr_traits_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.35"
rand = "0.8.5"
syn = { version = "2.0.52", features = ["full"] }

[dev-dependencies]
distr_traits = { path = "../" }
